### ISSUE TITLE
WFuzz Error

### ISSUE THREAD

**Issue by ChSotiriou** [AlexisAhmed/BugBountyToolkit#41]
The container was pulled directly from docker hub

```
[  9:24AM ]  [ root@70cce5c4a3f5:~/toolkit ]
 $ wfuzz
 /usr/local/lib/python2.7/dist-packages/wfuzz/__init__.py:35: UserWarning:Pycurl is not compiled against Openssl. Wfuzz might not work correctly when fuzzing SSL sites. Check Wfuzz's documentation for more information.
Traceback (most recent call last):
  File "/usr/local/bin/wfuzz", line 11, in <module>
    load_entry_point('wfuzz==3.1.0', 'console_scripts', 'wfuzz')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wfuzz/__init__.py", line 55, in <module>
    from .options import FuzzSession
  File "/usr/local/lib/python2.7/dist-packages/wfuzz/options.py", line 6, in <module>
    from .facade import (
  File "/usr/local/lib/python2.7/dist-packages/wfuzz/facade.py", line 65
    class Facade(metaclass=Singleton):
                          ^
SyntaxError: invalid syntax
```

**Comment by AlexisAhmed** [comment]
I am working on upgrading the package and fixing the issue.
